### PR TITLE
Some stuff I did when I didn’t know what else to do

### LINKED ISSUE #2: Client Crash on join
### Issue description
This is issue is a continuation of the last issue, on old repo.

When starting a server, and attempting to join the client will freeze at last stage then crash MC

- Expected result: Joining the world.
- Actual result: Client Crash

### Steps to reproduce the issue
1. Start Server
2. Join Server

### OS and versions
* PocketNode: 0.0.5 (All commits by TwistedAsylumMC)
* Node: 8.x, 9.x & 10.x
* Server OS: Windows
* Game version: PE and Win10

### Error log
N/A - Shows clients cause of disconnect as timeout.

### Extra Notes:
Please only comment on this issue if you find a suspect or culprit in code currently i believe its either Chunk formatting or a packet not being sent/handled correctly
But nothing has concrete evidence.

### PR DESCRIPTION
**Pull request by nobody5050**
### API changes

I changed the startup dialog from “pocketnode” to an ascii pocketnode

### Behavioural changes

Nope, just some suptuff with the demo plugin... idk nothing really

## Backwards compatibility

Everything is backwards compatible, all plugins should work, and I don’t think anything else needs to be changed

## Follow-up

I would suggest after merging this to make sure everything works and to also check that my ascii doesnt crash

## Tests

Run the server, if it works good if it doesn’t then revert this pull and I’ll fix it

### CODE REVIEW

**Comment by nobody5050** [comment]
Ok I’ll remove the ascii...

The Travis shows it didn’t work.

**Comment by nobody5050** [comment]
Removed ascii

Should be mergable now

**Comment by nobody5050** [comment]
It can be added as a plugin for changing Lang rather than having to edit the Lang file directly, just edit the plugin. Idk

**Comment by jackthehack21** [comment]
Doesn't do anything functional right now, would love a demo plugin that sends messages on player join and leave etc, possible command of ping, pong.
But this PR is useless

**Pull request closed without merging**
